### ISSUE TITLE
Can't load mod

### ISSUE THREAD

**Issue by enderger** [HarryTechRevs/MinecraftModding#10]
Crash report: https://gist.github.com/enderger/cff0cd632be6a4ef323478d0e34490b0
Mod: https://github.com/enderger/UOL

**Comment by HoneyFun** [comment]
I think it's just a random error. Every once in a while I used to get one of those errors when playing on my server. I hope this helps.

**Comment by enderger** [comment]
Happens 100% of the time

It is the blockores class and others

**Comment by HoneyFun** [comment]
So maybe your variants are causing the game to crash. I had that same problem when I first tried out variants.

**Comment by enderger** [comment]
fixed it, was enumrarity. I had to add     @Nonnull
